# Generated by Django 3.2.20 on 2023-07-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='event_location',
        ),
    ]
