# Generated by Django 3.2.20 on 2023-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230715_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Music', 'Music'), ('Culture', 'Culture'), ('Family', 'Family'), ('Food', 'Food'), ('Shopping', 'Shopping'), ('Sightseeing', 'Sightseeing')], default='Sightseeing', max_length=255),
        ),
    ]
