# Generated by Django 3.2.20 on 2023-07-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='social_media',
            field=models.TextField(blank=True),
        ),
    ]
